import hljs from "highlight.js/lib/core";
import bash from "highlight.js/lib/languages/bash";
import css from "highlight.js/lib/languages/css";
import javascript from "highlight.js/lib/languages/javascript";
import json from "highlight.js/lib/languages/json";
import markdown from "highlight.js/lib/languages/markdown";
import python from "highlight.js/lib/languages/python";
import typescript from "highlight.js/lib/languages/typescript";
import xml from "highlight.js/lib/languages/xml";
import DOMPurify from "dompurify";
import "katex/dist/katex.min.css";
import { Marked, Renderer } from "marked";
import type { Messages } from "../../src/shared/i18n";
import type { ChatSource } from "../../src/shared/types";
import { escapeHtml, markdownExtensions } from "./markdown-extensions";
import { applyStreamingTextRenderer } from "./markdown-streaming";

const markdownSanitizer = DOMPurify();
// Only generated image sources can retain blob URLs. All other attributes use
// DOMPurify's normal URI policy; raw model HTML is escaped before this boundary.
markdownSanitizer.addHook("uponSanitizeAttribute", (node, attribute) => {
  if (
    node.nodeName === "IMG" &&
    attribute.attrName === "src" &&
    /^blob:/i.test(attribute.attrValue) &&
    safeImageUrl(attribute.attrValue)
  )
    attribute.forceKeepAttr = true;
});

export type MarkdownSegment = {
  key: string;
  text: string;
  start: number;
  end: number;
};

hljs.registerLanguage("bash", bash);
hljs.registerLanguage("sh", bash);
hljs.registerLanguage("shell", bash);
hljs.registerLanguage("css", css);
hljs.registerLanguage("javascript", javascript);
hljs.registerLanguage("js", javascript);
hljs.registerLanguage("json", json);
hljs.registerLanguage("markdown", markdown);
hljs.registerLanguage("md", markdown);
hljs.registerLanguage("python", python);
hljs.registerLanguage("py", python);
hljs.registerLanguage("typescript", typescript);
hljs.registerLanguage("ts", typescript);
hljs.registerLanguage("tsx", typescript);
hljs.registerLanguage("html", xml);
hljs.registerLanguage("xml", xml);

export function renderMarkdown(
  text: string,
  t: Messages,
  copiedCodeId: string | null,
  sources: ChatSource[] = [],
  options: {
    animatedFromChar?: number;
    mermaidPreview?: boolean;
    syntaxHighlight?: boolean;
    codeIndexOffset?: number;
  } = {},
) {
  const codeBlocks: string[] = [];
  const renderer = new Renderer();
  // Model HTML is text, never extension UI. Math, citations and controls are
  // generated by typed renderers, so raw HTML cannot forge delegated actions.
  renderer.html = ({ text }) => escapeHtml(text);
  renderer.checkbox = ({ checked }) =>
    `<input type="checkbox" disabled${checked ? " checked" : ""}>`;
  if (options.animatedFromChar !== undefined)
    applyStreamingTextRenderer(renderer, options.animatedFromChar);
  renderer.image = ({ href, title, text }) =>
    renderMarkdownImage(href, title, text);
  renderer.code = ({ text: code, lang }) => {
    const localCodeIndex = codeBlocks.push(code) - 1;
    const codeIndex = (options.codeIndexOffset || 0) + localCodeIndex;
    const codeId = `code-${codeIndex}`;
    const copied = copiedCodeId === codeId;
    const language = lang?.split(/\s+/)[0] || "";
    const highlighted = options.syntaxHighlight
      ? highlightCode(code, language)
      : { html: escapeHtml(code), language };
    const displayLanguage = escapeHtml(
      language || highlighted.language || "text",
    );
    const preview = options.mermaidPreview
      ? mermaidPreview(code, language, t)
      : "";
    const source = preview
      ? ""
      : `<pre><code class="hljs${language ? ` language-${escapeHtml(language)}` : ""}">${highlighted.html}</code></pre>`;
    const copyLabel = copied ? t.common.copied : t.common.copy;
    return `<div class="markdown-code-block${copied ? " copied" : ""}"><div class="markdown-code-header"><span>${displayLanguage}</span><button type="button" class="code-copy" data-tooltip="${escapeHtml(copyLabel)}" data-code-index="${codeIndex}" data-code-id="${codeId}" aria-label="${escapeHtml(copyLabel)}"><svg class="code-copy-icon code-copy-copy" viewBox="0 0 24 24" aria-hidden="true"><rect x="9" y="9" width="11" height="11" rx="2"></rect><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"></path></svg><svg class="code-copy-icon code-copy-check" viewBox="0 0 24 24" aria-hidden="true"><path d="M20 6 9 17l-5-5"></path></svg></button></div>${preview}${source}</div>`;
  };
  const parser = new Marked({
    renderer,
    extensions: markdownExtensions(sources),
  });
  const html = markdownSanitizer.sanitize(
    parser.parse(text, { async: false }),
    {
      FORBID_TAGS: [
        "style",
        "form",
        "textarea",
        "select",
        "iframe",
        "object",
        "embed",
      ],
    },
  );
  return {
    html,
    codeBlocks,
  };
}

export function splitStreamingMarkdown(text: string, streaming: boolean) {
  if (!streaming) return [markdownSegment("full", text, 0, text.length)];
  const boundaries = stableMarkdownBoundaries(text);
  const segments: MarkdownSegment[] = [];
  let start = 0;
  for (const boundary of boundaries) {
    if (boundary <= start || boundary > text.length) continue;
    segments.push(
      markdownSegment(`stable:${start}:${boundary}`, text, start, boundary),
    );
    start = boundary;
  }
  if (start < text.length)
    segments.push(markdownSegment("live", text, start, text.length));
  return segments.length
    ? segments
    : [markdownSegment("live", text, 0, text.length)];
}

function markdownSegment(
  key: string,
  text: string,
  start: number,
  end: number,
) {
  return {
    key,
    text: text.slice(start, end),
    start,
    end,
  } satisfies MarkdownSegment;
}

function stableMarkdownBoundaries(text: string) {
  const boundaries: number[] = [];
  let lineStart = 0;
  let inFence: { marker: "`" | "~"; length: number } | undefined;
  let inDisplayMath = false;

  while (lineStart < text.length) {
    const newlineIndex = text.indexOf("\n", lineStart);
    const lineEnd = newlineIndex === -1 ? text.length : newlineIndex;
    const nextLineStart = newlineIndex === -1 ? text.length : newlineIndex + 1;
    const line = text.slice(lineStart, lineEnd);
    const fence = line.match(/^\s*(`{3,}|~{3,})/);

    if (fence) {
      const marker = fence[1][0] as "`" | "~";
      if (!inFence) {
        inFence = { marker, length: fence[1].length };
      } else if (
        inFence.marker === marker &&
        fence[1].length >= inFence.length
      ) {
        inFence = undefined;
        if (nextLineStart < text.length) boundaries.push(nextLineStart);
      }
    } else if (!inFence) {
      if (hasOddDisplayMathDelimiterCount(line)) inDisplayMath = !inDisplayMath;
      if (!inDisplayMath && /^\s*$/.test(line)) boundaries.push(nextLineStart);
    }

    lineStart = nextLineStart;
  }

  return boundaries.filter(
    (boundary, index) => boundary > 0 && boundaries.indexOf(boundary) === index,
  );
}

function hasOddDisplayMathDelimiterCount(line: string) {
  let count = 0;
  for (let index = 0; index < line.length - 1; index += 1) {
    if (line[index] !== "$" || line[index + 1] !== "$") continue;
    if (index > 0 && line[index - 1] === "\\") continue;
    count += 1;
    index += 1;
  }
  return count % 2 === 1;
}

function renderMarkdownImage(href: string, title: string | null, text: string) {
  const url = safeImageUrl(href);
  const alt = escapeHtml(text || title || "");
  if (!url) return `<span class="markdown-image-invalid">${alt}</span>`;
  return `<figure class="markdown-image-card"><img src="${escapeHtml(url)}" alt="${alt}" title="${escapeHtml(title || "")}" loading="lazy" referrerpolicy="no-referrer" /><figcaption>${alt}</figcaption></figure>`;
}

function safeImageUrl(href: string) {
  const value = href.trim();
  if (/^(https?:|data:image\/|blob:)/i.test(value)) return value;
  return "";
}

function mermaidPreview(code: string, language: string, t: Messages) {
  if (!isMermaidLanguage(language)) return "";
  const encoded = encodeMermaidState(code);
  const imageUrl = `https://mermaid.ink/svg/${encoded}?bgColor=transparent`;
  const pngUrl = `https://mermaid.ink/img/${encoded}?type=png&bgColor=transparent`;
  const viewUrl = `https://mermaid.live/view#base64:${encoded}`;
  return `<div class="mermaid-preview-panel"><a class="mermaid-preview ui-skeleton" href="${escapeHtml(viewUrl)}" title="${escapeHtml(t.sidepanel.openMermaidPreview)}"><img src="${escapeHtml(imageUrl)}" alt="${escapeHtml(t.sidepanel.mermaidPreview)}" loading="lazy" /></a><div class="mermaid-preview-actions"><button type="button" class="ui-button ui-button-secondary ui-button-sm" data-mermaid-download-url="${escapeHtml(imageUrl)}" data-mermaid-download-filename="mermaid-diagram.svg">${escapeHtml(t.sidepanel.downloadMermaidSvg)}</button><button type="button" class="ui-button ui-button-secondary ui-button-sm" data-mermaid-download-url="${escapeHtml(pngUrl)}" data-mermaid-download-filename="mermaid-diagram.png">${escapeHtml(t.sidepanel.downloadMermaidPng)}</button></div></div>`;
}

function isMermaidLanguage(language: string) {
  return ["mermaid", "mmd"].includes(language.toLowerCase());
}

function encodeMermaidState(code: string) {
  const state = JSON.stringify({
    code,
    mermaid: {
      theme: "base",
      themeVariables: mermaidThemeVariables(),
    },
  });
  const bytes = new TextEncoder().encode(state);
  let binary = "";
  for (let index = 0; index < bytes.length; index += 0x8000) {
    binary += String.fromCharCode(...bytes.subarray(index, index + 0x8000));
  }
  return btoa(binary)
    .replaceAll("+", "-")
    .replaceAll("/", "_")
    .replace(/=+$/, "");
}

function mermaidThemeVariables() {
  const style = getComputedStyle(document.documentElement);
  const color = (name: string, fallback: string) =>
    style.getPropertyValue(name).trim() || fallback;
  const background = color("--card", "#ffffff");
  const text = color("--foreground", "#161512");
  const muted = color("--muted-foreground", "#706d65");
  const accent = color("--accent-soft", "#f7e2ea");
  const accentStrong = color("--accent-strong", "#a35b76");
  const border = color("--border", "#e2e0d8");
  return {
    background,
    mainBkg: background,
    primaryColor: accent,
    primaryTextColor: text,
    primaryBorderColor: accentStrong,
    secondaryColor: color("--secondary", background),
    tertiaryColor: color("--accent-softer", background),
    lineColor: muted,
    textColor: text,
    nodeBorder: accentStrong,
    clusterBkg: background,
    clusterBorder: border,
    edgeLabelBackground: background,
    fontFamily: "Inter, ui-sans-serif, system-ui, sans-serif",
  };
}

function highlightCode(code: string, language: string) {
  try {
    if (language && hljs.getLanguage(language)) {
      return {
        html: hljs.highlight(code, { language, ignoreIllegals: true }).value,
        language,
      };
    }
    const result = hljs.highlightAuto(code);
    return { html: result.value, language: result.language || "" };
  } catch {
    return { html: escapeHtml(code), language: "" };
  }
}
