export const BROWSER_TOOL_NAME = {
  loadTools: "loadTools",
  question: "question",
  wait: "wait",
  startSubAgent: "startSubAgent",
  getSubAgentStatus: "getSubAgentStatus",
  startLocalExecutionBridge: "startLocalExecutionBridge",
  getLocalExecutionBridgeStatus: "getLocalExecutionBridgeStatus",
  cancelLocalExecutionBridge: "cancelLocalExecutionBridge",
  manageLocalExecutionBridges: "manageLocalExecutionBridges",
  getCurrentTime: "getCurrentTime",
  manageTabs: "manageTabs",
  getCurrentTab: "getCurrentTab",
  mutatePage: "mutatePage",
  inspectPage: "inspectPage",
  captureVisibleTab: "captureVisibleTab",
  cdpInput: "cdpInput",
  cdpPage: "cdpPage",
  cdpEvaluateScript: "cdpEvaluateScript",
  cdpExecuteArbitraryJavaScript: "cdpExecuteArbitraryJavaScript",
  cdpTakeScreenshot: "cdpTakeScreenshot",
  cdpDiagnostics: "cdpDiagnostics",
  cdpPerformanceStartTrace: "cdpPerformanceStartTrace",
  cdpPerformanceStopTrace: "cdpPerformanceStopTrace",
  cdpPerformanceAnalyzeInsight: "cdpPerformanceAnalyzeInsight",
  cdpTakeMemorySnapshot: "cdpTakeMemorySnapshot",
  cdpGetMemorySnapshotDetails: "cdpGetMemorySnapshotDetails",
  cdpGetNodesByClass: "cdpGetNodesByClass",
  cdpLoadMemorySnapshot: "cdpLoadMemorySnapshot",
  cdpLighthouseAudit: "cdpLighthouseAudit",
  cdpScreencastStart: "cdpScreencastStart",
  cdpScreencastStop: "cdpScreencastStop",
  downloadTabToMarkdown: "downloadTabToMarkdown",
  downloadAllImagesInTab: "downloadAllImagesInTab",
  readFileFromUrl: "readFileFromUrl",
  readUploadedAttachment: "readUploadedAttachment",
  manageSkills: "manageSkills",
  workspaceFiles: "workspaceFiles",
  manageMemory: "manageMemory",
  manageChatHistory: "manageChatHistory",
  manageMcpServers: "manageMcpServers",
  generateImage: "generateImage",
} as const;

export type BrowserToolName =
  (typeof BROWSER_TOOL_NAME)[keyof typeof BROWSER_TOOL_NAME];

export const UNKNOWN_TOOL_NAME = "unknown";
