export const BROWSER_TOOL_NAME = {
  loadBrowserTools: "loadBrowserTools",
  wait: "wait",
  getCurrentTime: "getCurrentTime",
  openNewTabWithURL: "openNewTabWithURL",
  getCurrentTab: "getCurrentTab",
  goToTab: "goToTab",
  insertCSSToTab: "insertCSSToTab",
  removeCSSToTab: "removeCSSToTab",
  getTabContent: "getTabContent",
  getAllTabs: "getAllTabs",
  closeTab: "closeTab",
  openSearchTab: "openSearchTab",
  waitTabLoadFinished: "waitTabLoadFinished",
  clickElementByAiID: "clickElementByAiID",
  cdpMouseActionByAiID: "cdpMouseActionByAiID",
  cdpClickAt: "cdpClickAt",
  cdpPressKey: "cdpPressKey",
  cdpTypeText: "cdpTypeText",
  cdpFill: "cdpFill",
  cdpFillForm: "cdpFillForm",
  cdpDrag: "cdpDrag",
  cdpHandleDialog: "cdpHandleDialog",
  cdpListPages: "cdpListPages",
  cdpNewPage: "cdpNewPage",
  cdpNavigatePage: "cdpNavigatePage",
  cdpSelectPage: "cdpSelectPage",
  cdpClosePage: "cdpClosePage",
  cdpWaitFor: "cdpWaitFor",
  cdpResizePage: "cdpResizePage",
  cdpEmulate: "cdpEmulate",
  cdpEvaluateScript: "cdpEvaluateScript",
  cdpExecuteArbitraryJavaScript: "cdpExecuteArbitraryJavaScript",
  cdpTakeScreenshot: "cdpTakeScreenshot",
  cdpTakeSnapshot: "cdpTakeSnapshot",
  cdpListConsoleMessages: "cdpListConsoleMessages",
  cdpGetConsoleMessage: "cdpGetConsoleMessage",
  cdpListNetworkRequests: "cdpListNetworkRequests",
  cdpGetNetworkRequest: "cdpGetNetworkRequest",
  cdpPerformanceStartTrace: "cdpPerformanceStartTrace",
  cdpPerformanceStopTrace: "cdpPerformanceStopTrace",
  cdpPerformanceAnalyzeInsight: "cdpPerformanceAnalyzeInsight",
  cdpTakeMemorySnapshot: "cdpTakeMemorySnapshot",
  cdpGetMemorySnapshotDetails: "cdpGetMemorySnapshotDetails",
  cdpGetNodesByClass: "cdpGetNodesByClass",
  cdpLoadMemorySnapshot: "cdpLoadMemorySnapshot",
  cdpLighthouseAudit: "cdpLighthouseAudit",
  cdpScreencastStart: "cdpScreencastStart",
  cdpScreencastStop: "cdpScreencastStop",
  inputTextByAiID: "inputTextByAiID",
  findAccessableElementsFromTab: "findAccessableElementsFromTab",
  getElementPropertiesByAiID: "getElementPropertiesByAiID",
  groupTabs: "groupTabs",
  scrollToBottom: "scrollToBottom",
  downloadTabToMarkdown: "downloadTabToMarkdown",
  downloadAllImagesInTab: "downloadAllImagesInTab",
  readFileFromUrl: "readFileFromUrl",
  readUploadedAttachment: "readUploadedAttachment",
  listSkills: "listSkills",
  readSkill: "readSkill",
  readSkillFile: "readSkillFile",
  updateSkillFile: "updateSkillFile",
  patchSkillFile: "patchSkillFile",
  listMcpServers: "listMcpServers",
  addMcpServer: "addMcpServer",
  updateMcpServer: "updateMcpServer",
  testMcpServer: "testMcpServer",
  deleteMcpServer: "deleteMcpServer",
  generateImage: "generateImage",
} as const;

export type BrowserToolName =
  (typeof BROWSER_TOOL_NAME)[keyof typeof BROWSER_TOOL_NAME];

export const UNKNOWN_TOOL_NAME = "unknown";
